### PR TITLE
Update Greetings

### PR DESCRIPTION
**Pull request by SunnySparks**
# 👨🏾‍💻 In this pull request, I have:

- Created a rails API called hello-rails-back-end
- Setup the database with Postgres
- Created an API endpoint that pulls data for 5 different greetings
- Link to hello-react-front-end pull request

[Link to frontend pull request](https://github.com/SunnySparks/hello-react-front-end/pull/2)

### CODE REVIEW

**Review by petudeveloper — CHANGES_REQUESTED** [review]
Hi @SunnySparks , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

I add these comments here because there was only one file changed:

- [x] Your database table for storing different greetings was not created, please add the necessary to add and set up it: 
  - Ther is no migration file for a table
  - There is no model created

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Invalid submission 

Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have all the changes in the commit form. Please make sure you do have all the changes in Pull Request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by enaburekhan — CHANGES_REQUESTED** [review]
Hi SunnySparks, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes

- [ ] I get the below error when I try to run your app. I will suggest you fix it. We can only approve a working app even if all the features have been implemented.

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by SunnySparks** [comment]
Hi @enaburekhan do you still have the same issue when running the app with the ruby version from the gem file? (2.7.2) I'm asking because I'm not able to reproduce the error on my, machine. The server runs correctly on my end

**Comment by enaburekhan** [comment]
@SunnySpark, I had to upgrade the ruby version to 3.0.0. Because I don't have 2,.7.2 installed on my machine. Maybe that could be the problem. I'm sorry about this. Kindly resubmit so it can be approved.

**Review by enaburekhan — APPROVED** [review]
Hi SunnySparks, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
